;;; mark-multiple-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from inline-string-rectangle.el

(autoload 'inline-string-rectangle "inline-string-rectangle" nil t)


;;; Generated autoloads from mark-more-like-this.el

(autoload 'mark-next-like-this "mark-more-like-this" "\
Find and mark the next part of the buffer matching the currently active region
With negative ARG, delete the last one instead.
With zero ARG, skip the last one and mark next.

(fn ARG)" t)
(autoload 'mark-previous-like-this "mark-more-like-this" "\
Find and mark the previous part of the buffer matching the currently active region
With negative ARG, delete the last one instead.
With zero ARG, skip the last one and mark previous.

(fn ARG)" t)
(autoload 'mark-all-like-this "mark-more-like-this" "\
Find and mark all the parts of the buffer matching the currently active region" t)
(autoload 'mark-all-like-this-in-region "mark-more-like-this" "\
Find and mark all the parts in the region matching the given search

(fn REG-START REG-END)" t)
(autoload 'mark-more-like-this "mark-more-like-this" "\
Marks next part of buffer that matches the currently active region ARG times.
Given a negative ARG it searches backwards instead.

(fn ARG)" t)
(autoload 'mark-more-like-this-extended "mark-more-like-this" "\
Like mark-more-like-this, but then lets you adjust with arrows key.
The actual adjustment made depends on the final component of the
key-binding used to invoke the command, with all modifiers removed:

   <up>    Mark previous like this
   <down>  Mark next like this
   <left>  If last was previous, skip it
           If last was next, remove it
   <right> If last was next, skip it
           If last was previous, remove it

Then, continue to read input events and further add or move marks
as long as the input event read (with all modifiers removed)
is one of the above." t)


;;; Generated autoloads from mark-multiple.el

(autoload 'mm/deactivate-region-or-clear-all "mark-multiple" "\
Deactivate mark if active, otherwise clear all." t)
(autoload 'mm/deactivate-region-and-clear-all "mark-multiple" "\
Deactivate mark and clear all." t)
(autoload 'mm/clear-all "mark-multiple" "\
Remove all marks" t)
(register-definition-prefixes "mark-multiple" '("mm/"))


;;; Generated autoloads from rename-sgml-tag.el

(autoload 'rename-sgml-tag "rename-sgml-tag" nil t)
(register-definition-prefixes "rename-sgml-tag" '("rst--inside-tag-p"))

;;; End of scraped data

(provide 'mark-multiple-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mark-multiple-autoloads.el ends here
